"""
Tests for vcamnamer.rule_applier
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import call, patch, MagicMock

import pytest

from vcamnamer.rule_applier import (
    _HEADER,
    _slugify,
    apply_rules,
    generate_rules,
    read_rules_file,
    remove_rules,
    rules_file_exists,
)


# ---------------------------------------------------------------------------
# _slugify tests
# ---------------------------------------------------------------------------


class TestSlugify:
    def test_simple_name(self):
        assert _slugify("OBS Camera") == "OBS_Camera"

    def test_special_chars_replaced(self):
        # trailing underscore from "!" is stripped
        assert _slugify("My Camera!") == "My_Camera"

    def test_spaces_replaced(self):
        assert _slugify("Presentation Cam") == "Presentation_Cam"

    def test_trailing_underscores_stripped(self):
        assert _slugify("  !!  ") == "vcam"

    def test_safe_chars_preserved(self):
        # Alphanumerics, hyphens, dots are preserved
        assert _slugify("Cam-1.2") == "Cam-1.2"

    def test_empty_string(self):
        assert _slugify("") == "vcam"


# ---------------------------------------------------------------------------
# generate_rules tests
# ---------------------------------------------------------------------------


class TestGenerateRules:
    def test_empty_mappings(self):
        result = generate_rules({})
        assert _HEADER in result
        assert "SUBSYSTEM" not in result

    def test_single_mapping(self):
        result = generate_rules({"/dev/video0": "OBS Studio Camera"})
        assert 'KERNEL=="video0"' in result
        assert 'SYMLINK+="vcam/OBS_Studio_Camera"' in result
        assert "video4linux" in result

    def test_multiple_mappings_sorted(self):
        result = generate_rules(
            {
                "/dev/video2": "Secondary",
                "/dev/video0": "Primary",
            }
        )
        lines = [l for l in result.splitlines() if "SUBSYSTEM" in l]
        assert "video0" in lines[0]
        assert "video2" in lines[1]

    def test_header_always_present(self):
        result = generate_rules({"/dev/video0": "Cam"})
        assert "AUTO-GENERATED by vcamnamer" in result

    def test_special_name_slugified_in_rule(self):
        result = generate_rules({"/dev/video0": "My Cam!"})
        assert "SYMLINK" in result
        # exclamation mark becomes underscore then trailing underscore is stripped
        assert "My_Cam" in result

    def test_rule_format(self):
        result = generate_rules({"/dev/video0": "Cam One"})
        # Must contain the full udev rule structure
        assert 'SUBSYSTEM=="video4linux"' in result
        assert 'KERNEL=="video0"' in result
        assert 'SYMLINK+="vcam/Cam_One"' in result


# ---------------------------------------------------------------------------
# apply_rules / remove_rules (filesystem + subprocess mocked)
# ---------------------------------------------------------------------------


@pytest.fixture()
def mock_rules_file(tmp_path: Path, monkeypatch):
    """Redirect RULES_FILE and RULES_DIR to a temp location."""
    import vcamnamer.rule_applier as ra

    monkeypatch.setattr(ra, "RULES_DIR", tmp_path)
    monkeypatch.setattr(ra, "RULES_FILE", tmp_path / "99-vcamnamer.rules")
    return tmp_path / "99-vcamnamer.rules"


@patch("vcamnamer.rule_applier.subprocess.run")
def test_apply_rules_writes_file(mock_run, mock_rules_file):
    mock_run.return_value = MagicMock(returncode=0)
    apply_rules({"/dev/video0": "My OBS Cam"})
    assert mock_rules_file.exists()
    content = mock_rules_file.read_text()
    assert "My_OBS_Cam" in content


@patch("vcamnamer.rule_applier.subprocess.run")
def test_apply_rules_calls_udevadm(mock_run, mock_rules_file):
    mock_run.return_value = MagicMock(returncode=0)
    apply_rules({"/dev/video0": "Cam"})
    # Should have called udevadm control --reload-rules and udevadm trigger
    assert mock_run.call_count == 2
    first_cmd = mock_run.call_args_list[0][0][0]
    assert "udevadm" in first_cmd[0]


@patch("vcamnamer.rule_applier.subprocess.run")
def test_remove_rules_deletes_file(mock_run, mock_rules_file):
    mock_run.return_value = MagicMock(returncode=0)
    # First create the file
    mock_rules_file.write_text("# test", encoding="utf-8")
    remove_rules()
    assert not mock_rules_file.exists()


@patch("vcamnamer.rule_applier.subprocess.run")
def test_remove_rules_noop_when_absent(mock_run, mock_rules_file):
    mock_run.return_value = MagicMock(returncode=0)
    remove_rules()  # file doesn't exist → no error, no udevadm call
    mock_run.assert_not_called()


def test_rules_file_exists_false(mock_rules_file):
    assert rules_file_exists() is False


@patch("vcamnamer.rule_applier.subprocess.run")
def test_rules_file_exists_true(mock_run, mock_rules_file):
    mock_run.return_value = MagicMock(returncode=0)
    apply_rules({"/dev/video0": "Cam"})
    assert rules_file_exists() is True


def test_read_rules_file_none_when_absent(mock_rules_file):
    assert read_rules_file() is None


@patch("vcamnamer.rule_applier.subprocess.run")
def test_read_rules_file_returns_content(mock_run, mock_rules_file):
    mock_run.return_value = MagicMock(returncode=0)
    apply_rules({"/dev/video0": "Cam"})
    content = read_rules_file()
    assert content is not None
    assert "Cam" in content


def test_write_rules_file_permission_error(monkeypatch, tmp_path):
    """_write_rules_file raises PermissionError with helpful message."""
    import vcamnamer.rule_applier as ra

    ro_dir = tmp_path / "ro"
    ro_dir.mkdir()
    monkeypatch.setattr(ra, "RULES_DIR", ro_dir)
    monkeypatch.setattr(ra, "RULES_FILE", ro_dir / "99-vcamnamer.rules")

    # Make the dir read-only
    ro_dir.chmod(0o555)
    try:
        with pytest.raises(PermissionError, match="Cannot write"):
            ra._write_rules_file("# test")
    finally:
        ro_dir.chmod(0o755)


# Need MagicMock imported at top level - already done above

