"""
rule_applier.py – Generate and manage udev rules for virtual-cam symlinks.

Strategy
--------
Linux does not expose an API to rename a /dev/videoN node in-place.
Instead we create **persistent udev symlinks** so that e.g.
``/dev/vcam/OBS_Studio_Camera`` → ``/dev/video0``.

A single rules file is written to::

    /etc/udev/rules.d/99-vcamnamer.rules

This file is *solely* managed by vcamnamer; it is clearly marked with a
header comment so users and sysadmins know it was auto-generated.

After writing the file the tool runs::

    udevadm control --reload-rules && udevadm trigger

which requires root (sudo).  If the caller does not have root the method
raises ``PermissionError`` with an actionable message.

Rollback
--------
``remove_rules()`` deletes the generated file and re-triggers udev, cleanly
removing all app-managed symlinks without touching other udev rules.
"""

from __future__ import annotations

import os
import re
import subprocess
import textwrap
from pathlib import Path
from typing import Dict, Optional

# ---------------------------------------------------------------------------
# Paths / constants
# ---------------------------------------------------------------------------

RULES_DIR = Path("/etc/udev/rules.d")
RULES_FILE = RULES_DIR / "99-vcamnamer.rules"

# Symlinks are created under this directory so they are clearly namespaced.
SYMLINK_DIR = "vcam"  # final path: /dev/vcam/<slug>

_HEADER = textwrap.dedent(
    """\
    # AUTO-GENERATED by vcamnamer – do not edit manually.
    # Remove with: sudo vcamnamer --reset-rules
    # Or delete this file and run: sudo udevadm control --reload-rules && sudo udevadm trigger
    """
)

# Characters not safe for a udev SYMLINK value / file-system name
_UNSAFE_RE = re.compile(r"[^A-Za-z0-9_\-.]")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _slugify(name: str) -> str:
    """
    Convert *name* to a file-system-safe slug for use as a symlink basename.

    Spaces and unsafe characters are replaced with underscores.
    Leading/trailing underscores are stripped.
    """
    slug = _UNSAFE_RE.sub("_", name.strip())
    return slug.strip("_") or "vcam"


def _bus_info_to_udev_attr(bus_info: str) -> Optional[str]:
    """
    Extract the platform/USB attribute from a bus_info string for udev matching.

    v4l2loopback devices report bus_info like ``platform:v4l2loopback-000``.
    USB cameras look like ``usb-0000:00:14.0-1``.
    Returns the raw bus_info string (used as ATTRS{bus_info} match).
    """
    return bus_info if bus_info else None


def _device_minor(node: str) -> Optional[int]:
    """Return the minor device number for a /dev/videoN node, or None."""
    try:
        return os.minor(os.stat(node).st_rdev)
    except OSError:
        return None


# ---------------------------------------------------------------------------
# Rule generation
# ---------------------------------------------------------------------------


def generate_rules(mappings: Dict[str, str]) -> str:
    """
    Build the text content of the udev rules file from *mappings*.

    *mappings* is ``{node: custom_name}``, e.g.
    ``{"/dev/video0": "OBS Studio Camera"}``.

    Each rule matches the device by its kernel subsystem + minor number
    (KERNEL=="video<N>") and creates a persistent symlink under /dev/vcam/.
    """
    lines = [_HEADER]
    for node, name in sorted(mappings.items()):
        slug = _slugify(name)
        kernel_name = os.path.basename(node)  # e.g. "video0"
        # Match by kernel name (stable for a given v4l2loopback slot) and
        # subsystem to avoid collisions with other char devices.
        rule = (
            f'SUBSYSTEM=="video4linux", KERNEL=="{kernel_name}", '
            f'SYMLINK+="{SYMLINK_DIR}/{slug}"'
        )
        lines.append(rule)
    lines.append("")  # trailing newline
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rule application / removal
# ---------------------------------------------------------------------------


def apply_rules(mappings: Dict[str, str]) -> None:
    """
    Write the udev rules file and reload udev.

    Raises
    ------
    PermissionError
        If the process does not have write access to RULES_DIR.
    subprocess.CalledProcessError
        If udevadm fails unexpectedly.
    """
    content = generate_rules(mappings)
    _write_rules_file(content)
    _reload_udev()


def remove_rules() -> None:
    """
    Delete the app-generated rules file and reload udev (rollback).

    No-op if the file does not exist.
    Raises PermissionError if we cannot delete the file.
    """
    if RULES_FILE.exists():
        try:
            RULES_FILE.unlink()
        except PermissionError:
            raise PermissionError(
                f"Cannot delete {RULES_FILE}. "
                "Please run: sudo vcamnamer --reset-rules\n"
                "Or manually: sudo rm /etc/udev/rules.d/99-vcamnamer.rules "
                "&& sudo udevadm control --reload-rules && sudo udevadm trigger"
            )
        _reload_udev()


def _write_rules_file(content: str) -> None:
    """Write *content* to RULES_FILE, raising PermissionError with guidance."""
    try:
        RULES_DIR.mkdir(parents=True, exist_ok=True)
        RULES_FILE.write_text(content, encoding="utf-8")
    except PermissionError:
        raise PermissionError(
            f"Cannot write to {RULES_FILE}. "
            "Please run vcamnamer with sudo, or grant write access to "
            f"{RULES_DIR}.\n"
            "Example: sudo vcamnamer --apply"
        )


def _reload_udev() -> None:
    """
    Reload udev rules and trigger re-evaluation of existing devices.

    Raises subprocess.CalledProcessError on failure.
    """
    try:
        subprocess.run(
            ["udevadm", "control", "--reload-rules"],
            check=True,
            capture_output=True,
            text=True,
        )
        subprocess.run(
            ["udevadm", "trigger", "--subsystem-match=video4linux"],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise RuntimeError(
            "udevadm not found. Please install udev (usually pre-installed on Ubuntu)."
        )


def rules_file_exists() -> bool:
    """Return True if the app-generated rules file is present on disk."""
    return RULES_FILE.exists()


def read_rules_file() -> Optional[str]:
    """Return the current content of the rules file, or None if absent."""
    try:
        return RULES_FILE.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
